### PR TITLE
Fix null safety in FlipTable.java

### PR DESCRIPTION
**Pull request by urosjarc**

### CODE REVIEW

**Comment by urosjarc** [comment]
@JakeWharton Also I want to thank you for producing this lovely library, I want to tell you that I have using your library in the following opensource application https://github.com/urosjarc/db-analyser

All the best!

**Comment by JakeWharton** [comment]
Makes sense. Thanks! I want to write a test tomorrow before merging though.

**Comment by JakeWharton** [comment]
Screwed up your branch accidentally which caused the PR to get closed. But I wrote a test, added a second place where this change was required, and landed on `master` as b50257869abcbea918471ddc61a8aa594a994f8c. Thanks!

**Comment by JakeWharton** [comment]
https://github.com/JakeWharton/flip-tables/releases/tag/1.1.1

**Comment by urosjarc** [comment]
@JakeWharton Thank you so much! Appreciated!

**Pull request closed without merging**
